baseURL = "http://sankalp.net/"
title = "S4NKALP"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
pygmentsStyle = "monokai"  # Code highlighting style
contentDir = "content"
enableGitInfo = true



[params]
  # Landing page
  ## Avatar
  avatarURL = "https://avatars.githubusercontent.com/u/98226895?v=4"
  AvatarAltText = "avatar"
  avatarSize = "size-l"  # size-xs, size-s, size-m, size-l & size-xl (default: size-m)
  ## Title
  description = "Thoughts of a Passion Driven Developer"
  ## Posts: "popular" (order posts by weight), "recent" (order posts by date) or "" (do not display, default option)
  showPostsOnHomePage = "recent"

  # Appearance
  ## Display "back to top" button on posts
  ShowBackToTopButton = true
  ## Date format
  dateFormat = "02.01.2006"
  ## Previous and Next buttons (will not work with the ".Weight" parameter)
  togglePreviousAndNextButtons = "false"
  footer = "S4NKALP"

  # Misc
  ## SEO
  metaKeywords = ["S4NKALP", "github", "tutorial", "blog"]


[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

   [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    pre = "<span data-feather='link'></span>"
    url = "https://S4NKALP.github.io/links"
    weight = 3


  [[menu.main]]
    name = "Github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/S4NKALP/"
    weight = 4

    [menu.main.params]
      newPage = true

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
